/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fitlifegym_presentacion;

/**
 *
 * @author Diego
 */
public class MenuRutinasClienteFORM extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuRutinasClienteFORM.class.getName());

    /**
     * Creates new form MenuRutinasClienteFORM
     */
    public MenuRutinasClienteFORM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lblTitulo = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        lblConsultarRutina = new javax.swing.JLabel();
        btnSeleccionarConsultarRutina = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        lblDescargar = new javax.swing.JLabel();
        btnSeleccionarDescargarRutina = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(18, 18, 18));
        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(225, 6, 0));
        jSeparator1.setForeground(new java.awt.Color(225, 6, 0));
        jPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 93, 960, 10));

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Arial", 3, 70)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Menú de Rutinas");
        jPanel.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 600, 94));

        jSeparator5.setBackground(new java.awt.Color(225, 6, 0));
        jSeparator5.setForeground(new java.awt.Color(225, 6, 0));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 180, 10, 270));

        lblConsultarRutina.setBackground(new java.awt.Color(255, 255, 255));
        lblConsultarRutina.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblConsultarRutina.setForeground(new java.awt.Color(255, 255, 255));
        lblConsultarRutina.setText("Consultar Rutina");
        jPanel.add(lblConsultarRutina, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 160, 40));

        btnSeleccionarConsultarRutina.setBackground(new java.awt.Color(255, 0, 51));
        btnSeleccionarConsultarRutina.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSeleccionarConsultarRutina.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarConsultarRutina.setText("Seleccionar");
        btnSeleccionarConsultarRutina.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSeleccionarConsultarRutina.addActionListener(this::btnSeleccionarConsultarRutinaActionPerformed);
        jPanel.add(btnSeleccionarConsultarRutina, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 187, 40));

        jSeparator6.setBackground(new java.awt.Color(225, 6, 0));
        jSeparator6.setForeground(new java.awt.Color(225, 6, 0));
        jPanel.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 240, -1));

        jSeparator7.setBackground(new java.awt.Color(225, 6, 0));
        jSeparator7.setForeground(new java.awt.Color(225, 6, 0));
        jPanel.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 240, -1));

        jSeparator8.setBackground(new java.awt.Color(225, 6, 0));
        jSeparator8.setForeground(new java.awt.Color(225, 6, 0));
        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 10, 270));

        jSeparator9.setBackground(new java.awt.Color(225, 6, 0));
        jSeparator9.setForeground(new java.awt.Color(225, 6, 0));
        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 10, 270));

        lblDescargar.setBackground(new java.awt.Color(255, 255, 255));
        lblDescargar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblDescargar.setForeground(new java.awt.Color(255, 255, 255));
        lblDescargar.setText("Descargar Rutina PDF");
        jPanel.add(lblDescargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 200, 40));

        btnSeleccionarDescargarRutina.setBackground(new java.awt.Color(255, 0, 51));
        btnSeleccionarDescargarRutina.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSeleccionarDescargarRutina.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarDescargarRutina.setText("Seleccionar");
        btnSeleccionarDescargarRutina.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSeleccionarDescargarRutina.addActionListener(this::btnSeleccionarDescargarRutinaActionPerformed);
        jPanel.add(btnSeleccionarDescargarRutina, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 187, 40));

        jSeparator10.setBackground(new java.awt.Color(225, 6, 0));
        jSeparator10.setForeground(new java.awt.Color(225, 6, 0));
        jPanel.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 240, -1));

        jSeparator11.setBackground(new java.awt.Color(225, 6, 0));
        jSeparator11.setForeground(new java.awt.Color(225, 6, 0));
        jPanel.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 240, -1));

        jSeparator12.setBackground(new java.awt.Color(225, 6, 0));
        jSeparator12.setForeground(new java.awt.Color(225, 6, 0));
        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, 10, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarConsultarRutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarConsultarRutinaActionPerformed
       
    }//GEN-LAST:event_btnSeleccionarConsultarRutinaActionPerformed

    private void btnSeleccionarDescargarRutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarDescargarRutinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarDescargarRutinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuRutinasClienteFORM().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionarConsultarRutina;
    private javax.swing.JButton btnSeleccionarDescargarRutina;
    private javax.swing.JPanel jPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblConsultarRutina;
    private javax.swing.JLabel lblDescargar;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
