/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.fitlifegym_presentacion;

import DTOS.EnfermedadesDTO;
import DTOS.EnfermedadesSeleccionadasDTO;
import DTOS.LesionesDTO;
import DTOS.LesionesSeleccionadasDTO;
import DTOS.RegistroFisicoDTO;
import com.mycompany.funcionalidadregistrofisico.RegistroFisicoException;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego
 */
public class RegistroFisicoConfirmarFORM extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroFisicoConfirmarFORM.class.getName());

    private ControlNavegacion controlNavegacion;
    private ControlRegistroFisico controlRegistroFisico;
    private RegistroFisicoDTO registroSinConfirmar;

    public RegistroFisicoConfirmarFORM(java.awt.Frame parent, boolean modal, ControlNavegacion controlNavegacion, ControlRegistroFisico controlRegistroFisico, RegistroFisicoDTO registroSinConfirmar) {
        super(parent, modal);
        this.controlNavegacion = controlNavegacion;
        this.controlRegistroFisico = controlRegistroFisico;
        this.registroSinConfirmar = registroSinConfirmar;
        this.setResizable(false);
        this.setTitle("Confirmar Registro Fisico");
        initComponents();
        this.setLocationRelativeTo(null);
        llenarTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lblTitulo = new javax.swing.JLabel();
        lblLimitacionesFisicas = new javax.swing.JLabel();
        lblNivelCondicion = new javax.swing.JLabel();
        lblEnfermedades = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        enfermedadesTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        limitacionesFisicasTable = new javax.swing.JTable();
        btnConfirmar = new javax.swing.JButton();
        lblCondicionEditable = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnVolverAtras3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(18, 18, 18));

        jSeparator1.setBackground(new java.awt.Color(225, 6, 0));
        jSeparator1.setForeground(new java.awt.Color(225, 6, 0));

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Arial", 3, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Confirmar Registro Físico");

        lblLimitacionesFisicas.setBackground(new java.awt.Color(255, 255, 255));
        lblLimitacionesFisicas.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblLimitacionesFisicas.setForeground(new java.awt.Color(255, 255, 255));
        lblLimitacionesFisicas.setText("Limitaciones Físicas:");

        lblNivelCondicion.setBackground(new java.awt.Color(255, 255, 255));
        lblNivelCondicion.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblNivelCondicion.setForeground(new java.awt.Color(255, 255, 255));
        lblNivelCondicion.setText("Nivel de Condición:");

        lblEnfermedades.setBackground(new java.awt.Color(255, 255, 255));
        lblEnfermedades.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblEnfermedades.setForeground(new java.awt.Color(255, 255, 255));
        lblEnfermedades.setText("Enfermedades:");

        jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane.setPreferredSize(new java.awt.Dimension(703, 573));

        enfermedadesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enfermedadesTable.setAutoscrolls(false);
        enfermedadesTable.getTableHeader().setResizingAllowed(false);
        enfermedadesTable.getTableHeader().setReorderingAllowed(false);
        enfermedadesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enfermedadesTableMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(enfermedadesTable);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(703, 573));

        limitacionesFisicasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        limitacionesFisicasTable.setAutoscrolls(false);
        limitacionesFisicasTable.getTableHeader().setResizingAllowed(false);
        limitacionesFisicasTable.getTableHeader().setReorderingAllowed(false);
        limitacionesFisicasTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limitacionesFisicasTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(limitacionesFisicasTable);

        btnConfirmar.setBackground(new java.awt.Color(255, 0, 51));
        btnConfirmar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnConfirmar.addActionListener(this::btnConfirmarActionPerformed);

        lblCondicionEditable.setBackground(new java.awt.Color(255, 255, 255));
        lblCondicionEditable.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblCondicionEditable.setForeground(new java.awt.Color(255, 255, 255));
        lblCondicionEditable.setText("Nivel de Condición:");

        btnCancelar.setBackground(new java.awt.Color(255, 0, 51));
        btnCancelar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnVolverAtras3.setBackground(new java.awt.Color(255, 0, 51));
        btnVolverAtras3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVolverAtras3.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverAtras3.setText("<");
        btnVolverAtras3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnVolverAtras3.addActionListener(this::btnVolverAtras3ActionPerformed);

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(lblNivelCondicion, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCondicionEditable, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addComponent(lblEnfermedades, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addComponent(lblLimitacionesFisicas, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(25, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addComponent(btnVolverAtras3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo))
                    .addComponent(btnVolverAtras3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lblLimitacionesFisicas)))
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEnfermedades)
                        .addGap(208, 208, 208))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)))
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNivelCondicion)
                            .addComponent(lblCondicionEditable))
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enfermedadesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enfermedadesTableMouseClicked

    }//GEN-LAST:event_enfermedadesTableMouseClicked

    private void limitacionesFisicasTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limitacionesFisicasTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_limitacionesFisicasTableMouseClicked

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        try {
            controlRegistroFisico.guardarRegistroFisico(registroSinConfirmar);
            controlNavegacion.navegarMenuRutinasCliente();
        } catch (RegistroFisicoException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        controlNavegacion.navegarMenuRutinasCliente();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnVolverAtras3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAtras3ActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnVolverAtras3ActionPerformed

    private void diseñoTablas() {
        enfermedadesTable.setRowHeight(40);
        enfermedadesTable.setBackground(new java.awt.Color(30, 30, 30));
        enfermedadesTable.setForeground(java.awt.Color.WHITE);
        enfermedadesTable.setGridColor(new java.awt.Color(225, 6, 0));

        enfermedadesTable.getTableHeader().setBackground(new java.awt.Color(30, 30, 30));
        enfermedadesTable.getTableHeader().setForeground(java.awt.Color.WHITE);
        enfermedadesTable.getTableHeader().setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));

        DefaultTableCellRenderer renderEnfermedades = new DefaultTableCellRenderer();
        renderEnfermedades.setHorizontalAlignment(JLabel.CENTER);
        enfermedadesTable.getColumnModel().getColumn(0).setCellRenderer(renderEnfermedades);

        limitacionesFisicasTable.setRowHeight(40);
        limitacionesFisicasTable.setBackground(new java.awt.Color(30, 30, 30));
        limitacionesFisicasTable.setForeground(java.awt.Color.WHITE);
        limitacionesFisicasTable.setGridColor(new java.awt.Color(225, 6, 0));
        jScrollPane2.getViewport().setBackground(new java.awt.Color(30, 30, 30));

        limitacionesFisicasTable.getTableHeader().setBackground(new java.awt.Color(30, 30, 30));
        limitacionesFisicasTable.getTableHeader().setForeground(java.awt.Color.WHITE);
        limitacionesFisicasTable.getTableHeader().setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));

        DefaultTableCellRenderer renderLimitaciones = new DefaultTableCellRenderer();
        renderLimitaciones.setHorizontalAlignment(JLabel.CENTER);
        limitacionesFisicasTable.getColumnModel().getColumn(0).setCellRenderer(renderLimitaciones);
        jScrollPane.getViewport().setBackground(new java.awt.Color(30, 30, 30));
    }

    public void llenarTablas() {
        List<EnfermedadesSeleccionadasDTO> enfermedadesSeleccionadasDTO = registroSinConfirmar.getEnfermedades();
        List<LesionesSeleccionadasDTO> lesionesSeleccionadasDTO = registroSinConfirmar.getLesiones();

        DefaultTableModel modeloEnfermedades = (DefaultTableModel) enfermedadesTable.getModel();
        modeloEnfermedades.setRowCount(0);
        for (EnfermedadesSeleccionadasDTO e : enfermedadesSeleccionadasDTO) {
            modeloEnfermedades.addRow(new Object[]{
                e.getNombre()
            });
        }

        DefaultTableModel modeloLesiones = (DefaultTableModel) limitacionesFisicasTable.getModel();
        modeloLesiones.setRowCount(0);
        for (LesionesSeleccionadasDTO l : lesionesSeleccionadasDTO) {
            modeloLesiones.addRow(new Object[]{
                l.getNombre()
            });
        }
        diseñoTablas();
        lblCondicionEditable.setText(registroSinConfirmar.getNivelCondicion().toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnVolverAtras3;
    private javax.swing.JTable enfermedadesTable;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCondicionEditable;
    private javax.swing.JLabel lblEnfermedades;
    private javax.swing.JLabel lblLimitacionesFisicas;
    private javax.swing.JLabel lblNivelCondicion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable limitacionesFisicasTable;
    // End of variables declaration//GEN-END:variables
}
