/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fitlifegym_presentacion;

import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Diego
 */
public class RegistroFisico extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroFisico.class.getName());

    private ControlNavegacion controlNavegacion;

    public RegistroFisico(ControlNavegacion controlNavegacion) {
        this.controlNavegacion = controlNavegacion;
        this.setResizable(false);
        this.setTitle("Registro Fisico");
        initComponents();
        diseñoTablas();
        tipoComboBox.setFocusable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lblTitulo = new javax.swing.JLabel();
        lblLimitacionesFisicas = new javax.swing.JLabel();
        lblNivelCondicion = new javax.swing.JLabel();
        lblEnfermedades = new javax.swing.JLabel();
        tipoComboBox = new javax.swing.JComboBox<>();
        jScrollPane = new javax.swing.JScrollPane();
        enfermedadesTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        limitacionesFisicasTable = new javax.swing.JTable();
        lblLeyendaCondicion = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(18, 18, 18));

        jSeparator1.setBackground(new java.awt.Color(225, 6, 0));
        jSeparator1.setForeground(new java.awt.Color(225, 6, 0));

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Arial", 3, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Registro Físico");

        lblLimitacionesFisicas.setBackground(new java.awt.Color(255, 255, 255));
        lblLimitacionesFisicas.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblLimitacionesFisicas.setForeground(new java.awt.Color(255, 255, 255));
        lblLimitacionesFisicas.setText("Limitaciones Físicas:");

        lblNivelCondicion.setBackground(new java.awt.Color(255, 255, 255));
        lblNivelCondicion.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblNivelCondicion.setForeground(new java.awt.Color(255, 255, 255));
        lblNivelCondicion.setText("Nivel de Condición:");

        lblEnfermedades.setBackground(new java.awt.Color(255, 255, 255));
        lblEnfermedades.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblEnfermedades.setForeground(new java.awt.Color(255, 255, 255));
        lblEnfermedades.setText("Enfermedades:");

        tipoComboBox.setBackground(new java.awt.Color(102, 102, 102));
        tipoComboBox.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tipoComboBox.setForeground(new java.awt.Color(255, 255, 255));
        tipoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BAJA", "INTERMEDIA", "AVANZADA" }));
        tipoComboBox.addActionListener(this::tipoComboBoxActionPerformed);

        jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane.setPreferredSize(new java.awt.Dimension(703, 573));

        enfermedadesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enfermedadesTable.setAutoscrolls(false);
        enfermedadesTable.getTableHeader().setResizingAllowed(false);
        enfermedadesTable.getTableHeader().setReorderingAllowed(false);
        enfermedadesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enfermedadesTableMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(enfermedadesTable);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(703, 573));

        limitacionesFisicasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        limitacionesFisicasTable.setAutoscrolls(false);
        limitacionesFisicasTable.getTableHeader().setResizingAllowed(false);
        limitacionesFisicasTable.getTableHeader().setReorderingAllowed(false);
        limitacionesFisicasTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limitacionesFisicasTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(limitacionesFisicasTable);

        lblLeyendaCondicion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblLeyendaCondicion.setText("LEYENDAAAAAAAAAA");

        btnGuardar.setBackground(new java.awt.Color(255, 0, 51));
        btnGuardar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(297, 297, 297))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addGap(0, 54, Short.MAX_VALUE)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(lblEnfermedades, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(lblLimitacionesFisicas, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(lblLeyendaCondicion, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 536, Short.MAX_VALUE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(lblNivelCondicion, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lblLimitacionesFisicas)))
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEnfermedades)
                        .addGap(176, 176, 176)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNivelCondicion)
                            .addComponent(tipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblLeyendaCondicion, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 246, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 863, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoComboBoxActionPerformed

    private void enfermedadesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enfermedadesTableMouseClicked


    }//GEN-LAST:event_enfermedadesTableMouseClicked

    private void limitacionesFisicasTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limitacionesFisicasTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_limitacionesFisicasTableMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        controlNavegacion.navegarRegistroFisicoConfirmar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void diseñoTablas() {
        enfermedadesTable.setRowHeight(40);
        enfermedadesTable.setBackground(new java.awt.Color(30, 30, 30));
        enfermedadesTable.setForeground(java.awt.Color.WHITE);
        enfermedadesTable.setGridColor(new java.awt.Color(225, 6, 0));

        enfermedadesTable.getTableHeader().setBackground(new java.awt.Color(30, 30, 30));
        enfermedadesTable.getTableHeader().setForeground(java.awt.Color.WHITE);
        enfermedadesTable.getTableHeader().setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));

        DefaultTableCellRenderer renderEnfermedades = new DefaultTableCellRenderer();
        renderEnfermedades.setHorizontalAlignment(JLabel.CENTER);
        enfermedadesTable.getColumnModel().getColumn(0).setCellRenderer(renderEnfermedades);

        limitacionesFisicasTable.setRowHeight(40);
        limitacionesFisicasTable.setBackground(new java.awt.Color(30, 30, 30));
        limitacionesFisicasTable.setForeground(java.awt.Color.WHITE);
        limitacionesFisicasTable.setGridColor(new java.awt.Color(225, 6, 0));

        limitacionesFisicasTable.getTableHeader().setBackground(new java.awt.Color(30, 30, 30));
        limitacionesFisicasTable.getTableHeader().setForeground(java.awt.Color.WHITE);
        limitacionesFisicasTable.getTableHeader().setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));

        DefaultTableCellRenderer renderLimitaciones = new DefaultTableCellRenderer();
        renderLimitaciones.setHorizontalAlignment(JLabel.CENTER);
        limitacionesFisicasTable.getColumnModel().getColumn(0).setCellRenderer(renderLimitaciones);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTable enfermedadesTable;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEnfermedades;
    private javax.swing.JLabel lblLeyendaCondicion;
    private javax.swing.JLabel lblLimitacionesFisicas;
    private javax.swing.JLabel lblNivelCondicion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable limitacionesFisicasTable;
    private javax.swing.JComboBox<String> tipoComboBox;
    // End of variables declaration//GEN-END:variables
}
